//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class demo
    {
        public long demo_Id { get; set; }
        public string demo_image { get; set; }
        public string demo_Url { get; set; }
        public string demo_Title { get; set; }
        public long demo_User { get; set; }
        public bool demo_IsDel { get; set; }
    
        public virtual User User { get; set; }
    }
}
