//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Articles = new HashSet<Article>();
            this.demoes = new HashSet<demo>();
        }
    
        public long User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Pwd { get; set; }
        public bool User_IsDel { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<demo> demoes { get; set; }
    }
}
